KS-20-5 String with help Lambda reverse
morrismag/StuduKotlin pull request #100
Opened 2023-06-02 12:55 UTC by morrismag

2023-06-03 11:03 UTC, ievetrov requested changes

2023-06-03 11:03 UTC, ievetrov commented on src/main/kotlin/lesson20/lesson_20_task_5.kt
> +    println(setModifier { say() })
> Программируем робота. Робот умеет говорить и работать с модификаторами речи. Речь реализуется методом say(). Модификатор устанавливается функцией setModifier(), принимающий лямбду.
> 
> Робот произносит одну из случайных 5 фраз (придумай фразы самостоятельно). Реализуй модификатор, инвертирующий слова робота.

В твоей текущей реализации в функция setModifier не устанавливает модификатор, а реверсит результат лямбды say. Нужно чтобы реверс производился в лямбде, которая в функции main() устанавливается.

И давай сразу сделаем классом Robot, внутри которого хранятся фразы и есть метод say, внутри которого применяется модификатор

2023-06-05 13:41 UTC, morrismag commented
Иван я не понимаю задания. Что такое "устанавливает модификатор"?. Что вообще такое модификатор?
Даже не знаю какой вопрос еще задать. Я не могу понять задания.

2023-06-06 09:15 UTC, ievetrov requested changes

2023-06-06 09:15 UTC, ievetrov commented on src/main/kotlin/lesson20/lesson_20_task_5.kt
> +        return listOf(
вынеси для начала список фраз в отдельную переменную внутри класса. чтобы облегчить восприятие

2023-06-06 09:15 UTC, ievetrov commented on src/main/kotlin/lesson20/lesson_20_task_5.kt
> +        return listOf(
этот метод делает 2 вещи
- берет рандомную фразу из списка
- вызывает print, в которую отправляется модификатор, принимающий эту строку

2023-06-06 09:15 UTC, ievetrov commented on src/main/kotlin/lesson20/lesson_20_task_5.kt
> +        return listOf(
что такое модификатор здесь – это поле класса, которое хранит "настройку" что нужно делать со строкой. по ТЗ это реверс, но может быть uppercase и все такое. Выглядеть он может так
`private var modifier: (String) -> String = { it }`

2023-06-06 09:15 UTC, ievetrov commented on src/main/kotlin/lesson20/lesson_20_task_5.kt
> +    fun setModifier(say: (String) -> Unit) {
"установка модификатора" не должна ничего печатать. это только настройка программы
```
fun setModifier(modifier: (String) -> String) {
    // здесь нужно присвоить данные из входящего модификатора из мейна – модификатору класса
}
```

2023-06-06 09:15 UTC, ievetrov commented on src/main/kotlin/lesson20/lesson_20_task_5.kt
> +    println( robotSay.say().reversed() )
в мейне должно работать примерно так:
- вызываешь say - функция печатает рандомную фразу
- вызываешь setModifier - устанавливаешь лямдбу, которая делает реверс входящей строки
- снова вызываешь say, чтобы убедиться, что печатается строка в реверсе

2023-06-07 09:40 UTC, morrismag commented
Иван к сожалению я не понимаю эту задачу. Мне попытались объяснить 3 программера, но я не могу вместить ее в мозг. Сейчас не перевертывает строку. Но даже то что написано мне не совсем понятно(((

2023-06-08 11:33 UTC, ievetrov commented
отписал в лс)

2023-06-08 11:38 UTC, ievetrov requested changes
отписал в лс)

2023-06-08 16:55 UTC, ievetrov commented on src/main/kotlin/lesson20/lesson_20_task_5.kt
> +        println(phraseRandom)
вот это даже лишнее мне кажется

просто вызови say() мейне еще раз ДО установки модификатора. так будет более чище выглядеть. мол вот фраза без, вот с изменением

но в целом хорошо, что разобрались. все четко!

2023-06-08 16:56 UTC, ievetrov approved these changes

2023-06-08 17:05 UTC, morrismag commented
Если убрать это будут разные фразы.

2023-06-09 08:26 UTC, merged