Lesson3 task3
morrismag/StuduKotlin pull request #13
Opened 2023-05-12 10:39 UTC by morrismag

2023-05-12 10:43 UTC, morrismag commented
Не понял почему изменилось название при пересылке.

2023-05-12 18:16 UTC, ievetrov requested changes
По условию функция print должна вызываться один раз

2023-05-12 18:19 UTC, ievetrov requested changes

2023-05-12 18:19 UTC, ievetrov commented on src/main/kotlin/lesson3/lesson_3_task_3.kt
> +//  что бы повторялась запись пока не введут и программа не завершалась.
таких требований условие не содержит) через цикл, но тема циклов будет в следующих уроках)

2023-05-12 18:19 UTC, ievetrov commented on src/main/kotlin/lesson3/lesson_3_task_3.kt
> +            println("$numberForCalculation x $i = $result")
функция print должна вызываться один раз, согласно условию

2023-05-13 11:21 UTC, ievetrov approved these changes
да, легально. или можно было использовать многострочный вывод
```
"""
    text
"""
```

2023-05-13 16:27 UTC, merged