KS-19-4 Best Tank shot
morrismag/StuduKotlin pull request #94
Opened 2023-05-31 10:57 UTC by morrismag

2023-06-01 09:48 UTC, ievetrov requested changes

2023-06-01 09:48 UTC, ievetrov commented on src/main/kotlin/lesson19/lesson_19_task_4.kt
> +    fun reloadingWeapons(): String {
reload звучит более корректно с точки зрения правил нейминга) (в инфинитиве)

2023-06-01 09:48 UTC, ievetrov commented on src/main/kotlin/lesson19/lesson_19_task_4.kt
> +enum class TypePatron {
а давай избавимся от множества функций внутри енам. 
а также цвет и дамаг будем хранить в свойствах енам класса. пусть логика стрельбы будет в классе танка

2023-06-01 15:26 UTC, morrismag commented on src/main/kotlin/lesson19/lesson_19_task_4.kt
> +enum class TypePatron {
Иван, я логики пока не понимаю зачем, а тем более реализации. Не могу понять что на выходе , как это будет выглядеть. Для меня этот класс как то вообще не очень, то заходите. Функции внутри хоть как то оправдывают его наличие. А если их убрать я не понимаю зачем он вообще в этой задаче.

2023-06-02 14:12 UTC, ievetrov requested changes

2023-06-02 14:12 UTC, ievetrov commented on src/main/kotlin/lesson19/lesson_19_task_4.kt
> +enum class TypePatron {
чтобы ответить на этот вопрос, стоит ответить на вопрос "зачем вообще нужен enum"

> Enum классы (от слова enumeration, что означает "перечисление") в программировании представляют собой специальный тип данных, который позволяет переменной быть набором предопределенных констант. Enum классы используются для создания группы именованных числовых констант.
> 
> Enum класс предоставляет эффективный, безопасный тип данных, который ограничивает его значения одним из заранее определенных. По сути, enum классы обеспечивают способ создания и использования константных значений, что обеспечивает удобочитаемый и надежный код.

то есть у нас есть ограниченный набор констант с определенными свойствами. это мы и реализуем)

2023-06-06 09:30 UTC, ievetrov approved these changes
отлично!

2023-06-06 09:46 UTC, merged