KS-19-5 Only two gender
morrismag/StuduKotlin pull request #95
Opened 2023-06-01 08:38 UTC by morrismag

2023-06-02 08:35 UTC, ievetrov requested changes

2023-06-02 08:35 UTC, ievetrov commented on src/main/kotlin/lesson19/lesson_19_task_5.kt
> +    var genderUser: String,
в нашей программе уже есть сущность (класс), для определения пола. предлагаю использовать его здесь)

2023-06-02 08:35 UTC, ievetrov commented on src/main/kotlin/lesson19/lesson_19_task_5.kt
> +        // val user = User(uName,uGender)
остался комментированный код

2023-06-02 08:35 UTC, ievetrov commented on src/main/kotlin/lesson19/lesson_19_task_5.kt
> +enum class Gender {
рекомендую в файле располагать сначала основные классы, затем вспомогательные, затем публичные функции, затем приватные. в руководстве по стилю нет конкретных требований на этот счет, но какой-то стиль для себя выбрать все же стоит

2023-06-02 08:35 UTC, ievetrov commented on src/main/kotlin/lesson19/lesson_19_task_5.kt
> +fun createCardUser(nameUser: String, genderUser: String): User {
функция, которая относится только к этому файлу уже может быть приватной

2023-06-05 10:37 UTC, morrismag commented
в нашей программе уже есть сущность (класс), для определения пола. предлагаю использовать его здесь)

Я пробывал по разному. Но ни как не могу readln() приравнять к Gender классу.

2023-06-06 09:45 UTC, ievetrov requested changes

2023-06-06 09:45 UTC, ievetrov commented on src/main/kotlin/lesson19/lesson_19_task_5.kt
> +            var genderUser: String,
тип гендера ставим из нашего enum
`var genderUser: Gender,`

чтобы явно указать, что user может хранить только ограниченное количество констант

2023-06-06 09:45 UTC, ievetrov commented on src/main/kotlin/lesson19/lesson_19_task_5.kt
> +private fun createCardUser(nameUser: String, genderUser:String): User {
тут соответственно тоже принимающий тип гендера будет Gender

2023-06-06 09:45 UTC, ievetrov commented on src/main/kotlin/lesson19/lesson_19_task_5.kt
> +            uGender = readln()
остается только распарсить значение, вводимое пользователем. потребуется дополнительное условие для сравнения ввода с названием поля из енам класса

2023-06-07 08:10 UTC, ievetrov requested changes

2023-06-07 08:10 UTC, ievetrov commented on src/main/kotlin/lesson19/lesson_19_task_5.kt
> +            else -> Gender.WOMAN
тут получается, что любой ввод кроме man, автоматически будет woman

2023-06-07 09:45 UTC, morrismag commented on src/main/kotlin/lesson19/lesson_19_task_5.kt
> +            else -> Gender.WOMAN
Иван , так проверкой сверху я в эту переменную только эти 2 значения и передаю. там просто по другому не даст выполниться дальше. Или тут в другом вопрос?

2023-06-08 12:17 UTC, ievetrov approved these changes

2023-06-08 12:17 UTC, ievetrov commented on src/main/kotlin/lesson19/lesson_19_task_5.kt
> +            else -> Gender.WOMAN
точно, сорри)) вопрос снят, все отлично

2023-06-08 16:23 UTC, merged